options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Copy project files from Cloud Storage to build environment
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'gs://bucket-0608a/django/bankingsystem-Dockerfile--main', '.']

  # Step 2: Upload the files to the VM instance
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute scp --recurse * sree@instance-0608a:/tmp --zone=us-central1-f

  # Step 3: Move files to the target directory with proper permissions
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh sree@instance-0608a --zone=us-central1-f --command "
          sudo mkdir -p /home/sree/ && \
          sudo mv /tmp/* /home/sree/ && \
          sudo chown -R sree:sree /home/sree/
        "

  # Step 4: Create the myenv directory, change ownership, and set permissions
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh sree@instance-0608a --zone=us-central1-f --command "
          sudo mkdir -p /home/sree/myenv && \
          sudo chown -R sree:sree /home/sree/myenv && \
          sudo chmod -R u+rwx /home/sree/myenv
        "

  # Step 5: Install Python, Django, Gunicorn, and Nginx
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh sree@instance-0608a --zone=us-central1-f --command "
          sudo apt update && \
          sudo apt install -y python3-pip python3-venv nginx && \
          sudo -u sree python3 -m venv /home/sree/myenv && \
          sudo -u sree /home/sree/myenv/bin/pip install django celery django_celery_beat gunicorn
        "

  # Step 6: Configure Nginx
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud compute ssh sree@instance-0608a --zone=us-central1-f --command "

        echo 'server {
          listen 80;
          server_name 34.136.99.124;
          location / {
            proxy_pass http://127.0.0.1:8000;
            proxy_set_header Host \$host;
            proxy_set_header X-Real-IP \$remote_addr;
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto \$scheme;
          }
        }' | sudo tee /etc/nginx/sites-available/bankingsystem && \
        sudo ln -sf /etc/nginx/sites-available/bankingsystem /etc/nginx/sites-enabled/bankingsystem && \
        sudo nginx -t && \
        sudo systemctl restart nginx
      "



  # Step 7: Start Gunicorn
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh sree@instance-0608a --zone=us-central1-f --command "
          cd /home/sree/bankingsystem-Dockerfile--main && \
          source /home/sree/myenv/bin/activate && \
          gunicorn --workers 3 --bind 0.0.0.0:8000 banking_system.wsgi:application
        "

# Optional: Set the timeout for the build (default is 10 minutes)
timeout: '1200s'
