options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Copy project files from Cloud Storage to build environment
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'gs://bucket-0708/django/bankingsystem-Dockerfile--main', '.']

  # Step 2: Upload the files to the VM instance
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Uploading files to VM instance..."
        gcloud compute scp --recurse * sree@instance-0808:/tmp --zone=us-central1-f

  # Step 3: Create new directory, move files, and set proper ownership
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Setting up directory structure..."
        gcloud compute ssh sree@instance-0808 --zone=us-central1-f --command "
          sudo rm -rf /home/sree/sri/ && \
          sudo mkdir -p /home/sree/sri && \
          sudo mv /tmp/* /home/sree/sri/ && \
          sudo chown -R sree:sree /home/sree/sri/
        "

  # Step 4: Create 'myenv' directory, set permissions
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating virtual environment..."
        gcloud compute ssh sree@instance-0808 --zone=us-central1-f --command "
          sudo mkdir -p /home/sree/sri/myenv && \
          sudo chown -R sree:sree /home/sree/sri/myenv && \
          sudo chmod -R u+rwx /home/sree/sri/myenv
        "

  # Step 5: Install Python, Django, Gunicorn, and Nginx
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing dependencies..."
        gcloud compute ssh sree@instance-0808 --zone=us-central1-f --command "
          sudo apt update && \
          sudo apt install -y python3-pip python3-venv nginx && \
          sudo -u sree python3 -m venv /home/sree/sri/myenv && \
          sudo -u sree /home/sree/sri/myenv/bin/pip install django celery django_celery_beat gunicorn
        "

  # Step 6: Configure Nginx
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Configuring Nginx..."
        gcloud compute ssh sree@instance-0808 --zone=us-central1-f --command "
          echo 'server {
            listen 80;
            server_name 34.69.99.157;
            location / {
              proxy_pass http://127.0.0.1:8000;
              proxy_set_header Host \$host;
              proxy_set_header X-Real-IP \$remote_addr;
              proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto \$scheme;
            }
          }' | sudo tee /etc/nginx/sites-available/bankingsystem && \
          sudo ln -sf /etc/nginx/sites-available/bankingsystem /etc/nginx/sites-enabled/bankingsystem && \
          sudo nginx -t && \
          sudo systemctl restart nginx
        "

  # Step 7: Create Systemd service file for Gunicorn
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating Systemd service file for Gunicorn..."
        gcloud compute ssh sree@instance-0808 --zone=us-central1-f --command "
          echo '[Unit]
          Description=Gunicorn instance to serve Django application
          After=network.target

          [Service]
          User=sree
          Group=sree
          WorkingDirectory=/home/sree/sri/bankingsystem-Dockerfile--main
          ExecStart=/home/sree/sri/myenv/bin/gunicorn --workers 3 --bind 0.0.0.0:8000 banking_system.wsgi:application
          Restart=always
          RestartSec=3

          [Install]
          WantedBy=multi-user.target' | sudo tee /etc/systemd/system/gunicorn.service && \
          sudo systemctl daemon-reload && \
          sudo systemctl enable gunicorn && \
          sudo systemctl start gunicorn
        "

# Optional: Set the timeout for the build (default is 10 minutes)
timeout: '600s'
